# Use the OS CSPRNG for cryptographic key/salt/IV generation; keep upstream pristine.
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/vendor/PDF4QT/Pdf4QtLibCore/sources/pdfsecurityhandler.cpp" security_source)
string(REPLACE "\r\n" "\n" security_source "${security_source}")
string(SHA256 security_hash "${security_source}")
if(NOT security_hash STREQUAL "cbd8cbb8bd2628c7a260ed215d7e6b24b6ff56785a8c81fa513cb15c3892734b")
    message(FATAL_ERROR "Review the security RNG adaptation for the new PDF4QT source")
endif()
string(REGEX MATCHALL "QRandomGenerator (randomNumberGenerator|generator) = QRandomGenerator::securelySeeded\\(\\)" rng_sites "${security_source}")
list(LENGTH rng_sites rng_count)
if(NOT rng_count EQUAL 4)
    message(FATAL_ERROR "Unexpected cryptographic RNG sites")
endif()
string(REGEX REPLACE "QRandomGenerator (randomNumberGenerator|generator) = QRandomGenerator::securelySeeded\\(\\);" "QRandomGenerator& \\1 = *QRandomGenerator::system();" security_source "${security_source}")
set(adapted_security "${CMAKE_BINARY_DIR}/adapted/pdfsecurityhandler.cpp")
if(EXISTS "${adapted_security}")
    file(READ "${adapted_security}" previous_security)
endif()
if(NOT security_source STREQUAL previous_security)
    file(WRITE "${adapted_security}" "${security_source}")
endif()
get_target_property(core_sources Pdf4QtLibCore SOURCES)
list(FIND core_sources "sources/pdfsecurityhandler.cpp" original_security_index)
if(original_security_index LESS 0)
    message(FATAL_ERROR "The original security source is missing from the target")
endif()
list(REMOVE_ITEM core_sources "sources/pdfsecurityhandler.cpp")
set_property(TARGET Pdf4QtLibCore PROPERTY SOURCES "${core_sources};${adapted_security}")
