# Preserve the pinned MIT implementation and add only a guarded identity path.
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/vendor/PDF4QT/Pdf4QtLibCore/sources/pdfcolorspaces.cpp" colorspace_source)
string(REPLACE "\r\n" "\n" colorspace_source "${colorspace_source}")
string(SHA256 colorspace_hash "${colorspace_source}")
if(NOT colorspace_hash STREQUAL "cf62ba9c975a8e74f1bb555e1afef75513bacb29102e2e71e1e2f37c9598a213")
    message(FATAL_ERROR "Review the image conversion adaptation for the new PDF4QT source")
endif()
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/vendor/PDF4QT/Pdf4QtLibCore/sources/pdfcms.cpp" cms_source)
string(REPLACE "\r\n" "\n" cms_source "${cms_source}")
string(SHA256 cms_hash "${cms_source}")
if(NOT cms_hash STREQUAL "8fbcf2e0f99a5399809fdb730e39e6f93564bccc52ad547cd22464af45f8a866")
    message(FATAL_ERROR "The generic CMS identity conversion must be reviewed")
endif()
string(REPLACE "#include \"pdfcolorspaces.h\""
    "#include \"pdfcolorspaces.h\"\n#include \"device_image_decode.h\""
    colorspace_source "${colorspace_source}")
set(identity_anchor "    if (imageData.isValid())\n    {\n        switch (imageData.getMaskingType())")
string(FIND "${colorspace_source}" "${identity_anchor}" identity_anchor_index)
if(identity_anchor_index LESS 0)
    message(FATAL_ERROR "The pinned image conversion entry is missing")
endif()
string(REPLACE "${identity_anchor}"
    "    if (auto identity = tatsu::tryDecodeDeviceImage(*this, imageData, cms, operationControl))\n        return *identity;\n${identity_anchor}"
    colorspace_source "${colorspace_source}")
set(adapted_colorspace "${CMAKE_BINARY_DIR}/adapted/pdfcolorspaces.cpp")
if(EXISTS "${adapted_colorspace}")
    file(READ "${adapted_colorspace}" previous_colorspace)
endif()
if(NOT colorspace_source STREQUAL previous_colorspace)
    file(WRITE "${adapted_colorspace}" "${colorspace_source}")
endif()
get_target_property(core_sources Pdf4QtLibCore SOURCES)
list(FIND core_sources "sources/pdfcolorspaces.cpp" original_colorspace_index)
if(original_colorspace_index LESS 0)
    message(FATAL_ERROR "The original colorspace source is missing from the target")
endif()
list(REMOVE_ITEM core_sources "sources/pdfcolorspaces.cpp")
set_property(TARGET Pdf4QtLibCore PROPERTY SOURCES "${core_sources};${adapted_colorspace}")
target_sources(Pdf4QtLibCore PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src/device_image_decode.cpp")
target_include_directories(Pdf4QtLibCore PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
