# Preserve serialized CropBox geometry without editing the pinned upstream tree.
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/vendor/PDF4QT/Pdf4QtLibCore/sources/pdfdocumentwriter.cpp" writer_source)
string(REPLACE "\r\n" "\n" writer_source "${writer_source}")
string(SHA256 writer_hash "${writer_source}")
if(NOT writer_hash STREQUAL "f1c0e55f44c2707e1c2076c75ef1e3aa60cb00998fb3233d823baedb04ed852d")
    message(FATAL_ERROR "Review the numeric writer adaptation for the new PDF4QT source")
endif()
set(original_real "QString::number(value, 'f', 5)")
string(FIND "${writer_source}" "${original_real}" original_real_index)
if(original_real_index LESS 0)
    message(FATAL_ERROR "The pinned real-number writer is missing")
endif()
string(REPLACE "${original_real}" "QString::number(value, 'f', 10)" writer_source "${writer_source}")
string(REPLACE "// Jakub Melka: we use 5 digits, because they are specified" "// PDF Tatsujin: retain 10 fractional digits in the file. Viewer arithmetic\n    // may have lower precision; Appendix C describes those implementation limits.\n    // Original upstream note: we use 5 digits, because they are specified" writer_source "${writer_source}")
set(adapted_writer "${CMAKE_BINARY_DIR}/adapted/pdfdocumentwriter.cpp")
if(EXISTS "${adapted_writer}")
    file(READ "${adapted_writer}" previous_writer)
endif()
if(NOT writer_source STREQUAL previous_writer)
    file(WRITE "${adapted_writer}" "${writer_source}")
endif()
get_target_property(core_sources Pdf4QtLibCore SOURCES)
list(FIND core_sources "sources/pdfdocumentwriter.cpp" original_writer_index)
if(original_writer_index LESS 0)
    message(FATAL_ERROR "The original document writer source is missing from the target")
endif()
list(REMOVE_ITEM core_sources "sources/pdfdocumentwriter.cpp")
set_property(TARGET Pdf4QtLibCore PROPERTY SOURCES "${core_sources};${adapted_writer}")
target_include_directories(Pdf4QtLibCore PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/vendor/PDF4QT/Pdf4QtLibCore/sources")
